_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
Continue:
    value: "False"
HotEncoding:
    value: "On"
Ks:
    value: 3
Kt:
    value: 3
act_func:
    value: glu
batch_size:
    value: 16
complexity:
    value: 4
dataset:
    value: seoul
droprate:
    value: 0.01
enable_bias:
    value: true
enable_cuda:
    value: true
epochs:
    value: 1000
fname:
    value: K460_16base_S220samp_seq_lr0.0001_0112p
gamma:
    value: 0.95
graph_conv_type:
    value: OSA
gso_type:
    value: sym_norm_lap
k_threshold:
    value: 460
lr:
    value: 0.0001
mode:
    value: train
n_his:
    value: 24
n_pred:
    value: 3
opt:
    value: adamw
patience:
    value: 10
seed:
    value: 42
stblock_num:
    value: 5
step_size:
    value: 18
time_intvl:
    value: 5
weight_decay_rate:
    value: 0
